/* automatically generated by version.py - do not edit! */

#include "version.h"

static char version[] = "APULLIN-OCTOROACH-MASTER;PID-HARD;STEER-HARD: Wed Jul 11 01:41:48 2012";

char* versionGetString(void) { return version; }
