/* automatically generated by version.py - do not edit! */

#include "version.h"

static char version[] = "APULLIN-OCTOROACH-DEVEL;LEGPID-HARD;STEERPID-HARD: Thu Jun 21 20:13:15 2012";

char* versionGetString(void) { return version; }