/* automatically generated by version.py - do not edit! */

#include "version.h"

static char version[] = "APULLIN-OCTOROACH-MASTER;PID-HARD;STEER-HARD: Mon Jul 23 18:43:40 2012";

char* versionGetString(void) { return version; }
